version: "3.9"

services:
  mindsdb:
    image: mindsdb/mindsdb
    container_name: mindsdb_container
    ports:
      - "47334:47334"
      - "47335:47335"
    volumes:
      - ./backend/mdb_data:/root/mdb_storage
    networks:
      - simplifai_network

  ollama:
    image: ollama/ollama
    container_name: ollama_container
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    # comment out this deploy part for cpu only
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${DOCKER_DRIVER:-nvidia}
              count: 0
              capabilities: ["${SOME_VALUE:-gpu}"]
    networks:
      - simplifai_network
    command: ollama pull anoob/simp2

  frontend:
    build: "./frontend/"
    container_name: simplifai_frontend
    ports:
      - 5173:5173
    networks:
      - simplifai_network

  backend:
    build: "./backend/"
    container_name: simplifai_backend
    ports:
      - 8000:8000
    environment:
      MINDS_DB: http://mindsdb:47334
    depends_on:
      - mindsdb
    networks:
      - simplifai_network

volumes:
  ollama:

networks:
  simplifai_network:
    driver: bridge
