version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_container
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${DOCKER_DRIVER:-nvidia}
              count: 0
              capabilities: ["${SOME_VALUE:-gpu}"]
    networks:
      - simplifai_network

  model-puller:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - ollama
    command: >
      sh -c "
        # Wait for Ollama to be ready
        while ! wget -q --spider http://ollama:11434/api/tags; do
          echo 'Waiting for Ollama to be ready...'
          sleep 1
        done
        echo 'Ollama is ready. Pulling model...'
        # Run the model pull command in the Ollama container
        docker exec ollama_container ollama pull anoob/simp2
      "
    networks:
      - simplifai_network
  
volumes:
  ollama:

networks:
  simplifai_network:
    driver: bridge
