# Generated by Django 5.0.6 on 2024-06-19 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('isUser', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot', models.ImageField(blank=True, null=True, upload_to='report/')),
                ('date', models.DateField()),
            ],
        ),
    ]
