# Generated by Django 5.0.6 on 2024-06-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
